### ISSUE TITLE
UnboundLocalError: local variable 'emotion_distribution' referenced before assignment

### ISSUE THREAD

**Issue by ditto66** [BetterZH/SEVLM-for-Visual-Art-Comprehension#1]
Hi, I am facing the mentioned Error while I run the training command, training get started:
`accelerate launch artEmisX_train.py --ckpt_path /xxxx/ckpts/  --caption_save_path /xxxx/results/  --nle_data_train_path /xxxx/data/artEmis/artEmisX_cl_train.json  --nle_data_val_path /xxxx/data/artEmis/artEmisX_val.json`

But then I have faced the followed error:

File "SEVLM-for-Visual-Art-Comprehension/utils/datasets.py", line 171, in __getitem__
    emotion_distribution = torch.stack([emotion_distribution,emotion_distribution])
UnboundLocalError: local variable 'emotion_distribution' referenced before assignment

Can you help fix that?
Thank you!

**Comment by BetterZH** [comment]
Thanks for your reminder, I have fixed this issue. If you have other questions, please feel free to discuss.
